### ISSUE TITLE
improve readme.md

### ISSUE THREAD

**Issue by SAHU-01** [SAHU-01/Github-demo-2#1]
I want contributors to improve my readme file.

**Comment by Vatsyayan-Siddhant** [comment]
I want to work on this

**Comment by noobcoder02** [comment]
//cc @SAHU-01 I want to work on this project. I had good experience with markdown. I'll try my level best to submit.

**Comment by anishapattanaik** [comment]
@SAHU-01 I want to work on this.

**Comment by diyak19** [comment]
Allow me to work on this.

**Comment by SAHU-01** [comment]
> Allow me to work on this.

you can go ahead and collaborate with @Vatsyayan-Siddhant @noobcoder02 refer and ask them

**Comment by diyak19** [comment]
@Vatsyayan-Siddhant Can we work?

**Comment by anishapattanaik** [comment]
@Vatsyayan-Siddhant can we work?

**Comment by anishapattanaik** [comment]
Srujan can we work?

**Comment by diyak19** [comment]
Srujan can we work?

**Comment by noobcoder02** [comment]
@Vatsyayan-Siddhant allow me to work on it

**Comment by SHRUTIP2307** [comment]
@SAHU-01 i want to work on this issue

**Comment by SAHU-01** [comment]
> @SAHU-01 i want to work on this issue

Hey @SHRUTIP2307  great plz start working!
